---
# For configuration options and examples, please see:
# https://gethomepage.dev/configs/services/
- Media:
    - Jellyfin:
        icon: jellyfin.png
        href: https://jellyfin.hydra14.com
        description: Watch movies and TV shows
        server: my-docker
        container: jellyfin
        widget:
            type: jellyfin
            url: http://jellyfin:8096
            key: bc0104721e1841fe81f71570afa34930
            enableBlocks: true # optional, defaults to false
            enableNowPlaying: true # optional, defaults to true
            enableUser: true # optional, defaults to false
            showEpisodeNumber: true # optional, defaults to false
            expandOneStreamToTwoRows: false # optional, defaults to true
    - Overseerr:
        icon: jellyseerr.png
        href: https://jellyseerr.hydra14.com
        description: Request movies and TV shows
        server: my-docker
        container: jellyseerr
        widget:
            type: jellyseerr
            url: http://jellyseerr:5055
            key: MTc0ODYzNzI0MDIxOTI0YzdmZWU5LWZhZDYtNDkyYy1hNDYyLWUyYmM0N2YyYTIxMg==
    - Immich:
        icon: immich.png
        href: https://immich.hydra14.com
        description: Photos and Videos
        server: my-docker
        container: immich_server
        widget:
            type: immich
            url: http://110.10.0.101:2283
            key: y3rqBBqJ1yqhgHJWec54dWYH3j9eerNqukhoNFtzM
            version: 2
    - Paperless:
        icon: paperless-ngx.png
        href: https://docs.hydra14.com
        description: Papers and documents
        server: my-docker
        container: paperless-webserver-1
        widget:
            type: paperlessngx
            url: http://110.10.0.101:8123
            key: 7cf5137d34d8c3fb1a80be217e018bf8e1d874c2
- Backend:
    - Radarr:
        icon: radarr.png
        href: https://radarr.hydra14.com
        description: Manage movies
        server: my-docker
        container: radarr
        widget:
            type: radarr
            url: http://radarr:7878
            key: b6303d83c83d40e5bbfd88fbcd274826
            enableQueue: true
    - Sonarr:
        icon: sonarr.png
        href: https://sonarr.hydra14.com
        description: Manage TV shows
        server: my-docker
        container: sonarr
        widget:
            type: sonarr
            url: http://sonarr:8989
            key: 16b8a509592e4c4193edfdf3655784ab
            enableQueue: true
    - Prowlarr:
        icon: prowlarr.png
        href: https://prowlarr.hydra14.com
        description: Indexer for movies and TV shows
        server: my-docker
        container: prowlarr
        widget:
            type: prowlarr
            url: http://prowlarr:9696
            key: f9b1463d38df41c7a9a884063e7f02ae
    - qbittorrent:
        icon: qbittorrent.png
        href: https://qbittorrent.hydra14.com
        description: Manage downloads
        server: my-docker
        container: qbittorrent
        widget:
            type: qbittorrent
            url: http://qbittorrent:8080
            username: hydra14
            password: Welding14
            enableLeechProgress: true # optional, defaults to false
    - portainer:
        icon: portainer.png
        href: https://port.hydra14.com
        description: Docker manager
        server: my-docker
        container: portainer
        widget:
            type: portainer
            url: http://portainer:9000
            env: 3
            key: ptr_xZYNCJtUqcmjAjEjEYvxUrOZHDbhkbrzMUr6plVESes=
